// Code generated by hertz generator.

package main

import (
	"context"
	handler "ghkd/module/api/biz/handler"
	"ghkd/module/api/biz/handler/api"
	"ghkd/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		api.SendResponse(c, errno.ServiceErr, nil)
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) {
		api.SendResponse(c, errno.ServiceErr, nil)
	})
}
